module.exports = [{
	"field_org_nid": "327686",
	"field_org_id": "117162",
	"title_field": "Mahyar Eidgah Family Medicine and Primary Care",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "310 E 14th St",
	"field_org_street2": "3rd FL",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10003",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (646) 859-6234 (Main)\n\n",
	"field_org_lat_long": "40.731948700000, -73.984588200000",
	"field_org_distance": "0.15",
	"field_org_last_updated": "2018-06-25 09:45",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "",
	"field_audiences": "At Risk Persons, General Public",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/327686",
	"field_organization_hours": "Monday,8:15am To 4:45pm, Tuesday,8:15am To 6:15pm, Wednesday,8:15am To 4:45pm, Thursday,8:15am To 6:15pm, Friday,8:15am To 4:45pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "Fee",
	"field_org_emails": "",
	"last_updated": "4/2/20",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.doctoreidgah.com||"
}, {
	"field_org_nid": "327751",
	"field_org_id": "117145",
	"title_field": "Saint Marks Institute for Health/Unitas NYC",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "57 St Marks Pl",
	"field_org_street2": "",
	"field_org_city_name": "New York City",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10003",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 982-3470 (Main)\n\n",
	"field_org_lat_long": "40.728271700000, -73.986423400000",
	"field_org_distance": "0.28",
	"field_org_last_updated": "2018-04-27 09:30",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Substance Abuse Treatment, Primary Care, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), Hepatitis C Treatment",
	"field_org_svc_support": "",
	"field_audiences": "At Risk Persons, General Public, LGBT",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/327751",
	"field_organization_hours": "",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicaid Accepted",
	"field_org_emails": "st.marks@unitas-nyc.org",
	"last_updated": "3/24/20",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.unitas-nyc.org||"
}, {
	"field_org_nid": "307761",
	"field_org_id": "112419",
	"title_field": "Mount Sinai ",
	"field_organization_name_2": "Peter Krueger Clinic",
	"field_organization_name_3": "",
	"field_org_street1": "317 E 17th St",
	"field_org_street2": "Fierman Hall 1st Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10003",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 420-2620 (Main)\n\n",
	"field_org_lat_long": "40.734175900000, -73.982687000000",
	"field_org_distance": "0.28",
	"field_org_last_updated": "2017-09-01 00:00",
	"field_org_svc_testing": "Hepatitis B Testing, Hepatitis C Testing, Conventional Blood HIV Testing, Rapid Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Herpes Testing, Syphilis Testing, TB Testing",
	"field_org_svc_prevention": "Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Family Planning, Human Papillomavirus Vaccine, STD Treatment, Primary Care, Medication Adherence Education and Counseling, Pre-Exposure Prophylaxis (PrEP), Clinical Trials, HIV/AIDS Medical Treatment, Dental Care, Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Hepatitis B Treatment, Hepatitis C Treatment",
	"field_org_svc_support": "Case Management, Drug Purchasing Assistance, including AIDS Drug Purchasing Assistance (ADAP), PrEP Navigation",
	"field_audiences": "Adults, African Americans/Blacks, Gay Men, Hispanics/Latinos, HIV Positive Persons, Homeless Persons, Injecting Drug Users/Needle Sharing Partners, LGBT, Low Income Persons, Men, Persons with Hepatitis, Persons with HIV/AIDS, Persons with TB, Substance Abusers, Women",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/307761",
	"field_organization_hours": "",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Donations Accepted,Fee,Free HIV Testing,Insurance Accepted,Medicaid Accepted,Medicare Accepted",
	"field_org_emails": "IAMListening@mountsinai.org",
	"last_updated": "11/19/19",
	"field_org_type": "Clinic,Hospital",
	"field_org_websites": "https://www.mountsinai.org/patient-care/iam||"
}, {
	"field_org_nid": "326970",
	"field_org_id": "116335",
	"title_field": "Astor Medical",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "67 Irving Pl",
	"field_org_street2": "5th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10003",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 253-2968 (Main)\n\n",
	"field_org_lat_long": "40.736703400000, -73.987025300000",
	"field_org_distance": "0.31",
	"field_org_last_updated": "2017-10-12 00:00",
	"field_org_svc_testing": "Conventional Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Syphilis Testing",
	"field_org_svc_prevention": "HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "STD Treatment, Primary Care, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "At Risk Persons, Persons with HIV/AIDS",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/326970",
	"field_organization_hours": "Monday,10:00am To 6:00pm, Tuesday,10:00am To 6:00pm, Wednesday,10:00am To 6:00pm, Thursday,10:00am To 6:00pm, Friday,9:00am To 4:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicare Accepted",
	"field_org_emails": "",
	"last_updated": "10/17/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.astormedical.com||"
}, {
	"field_org_nid": "322346",
	"field_org_id": "113989",
	"title_field": "Hetrick-Martin Institute",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "2 Astor Pl",
	"field_org_street2": "3rd Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10003",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 674-2400 (Main)\n\n",
	"field_org_lat_long": "40.729879100000, -73.992583100000",
	"field_org_distance": "0.32",
	"field_org_last_updated": "2017-07-12 00:00",
	"field_org_svc_testing": "Rapid Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Syphilis Testing",
	"field_org_svc_prevention": "Behavioral Interventions, HIV/AIDS Prevention Education, STD Prevention/Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "",
	"field_org_svc_support": "Case Management, Housing Opportunities for Persons with AIDS/HOPWA",
	"field_audiences": "Adolescents/Youth/Teens, LGBT, Persons with STDs",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/322346",
	"field_organization_hours": "Monday,10:00am To 6:00pm, Tuesday,10:00am To 6:00pm, Wednesday,10:00am To 6:00pm, Thursday,10:00am To 6:00pm, Friday,10:00am To 6:00pm",
	"field_organization_eligibilty": "Youth, Ages 16-24. HMI offers additional services, including general healthcare referrals; mental health and case management; food and hygiene products/facilities; housing assistance; employment services; & academic enrichment.",
	"field_org_fee": "lowcost,Free HIV Testing,Free STD Testing,No Fee",
	"field_org_emails": "",
	"last_updated": "7/22/19",
	"field_org_type": "Community Based Organization,",
	"field_org_websites": "https://hmi.org||, https://www.facebook.com/HetrickMartin||"
}, {
	"field_org_nid": "344411",
	"field_org_id": "344411",
	"title_field": "CVS MinuteClinic",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "215 Park Ave S",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "",
	"field_org_state": "NY",
	"field_org_zipcode": "10003",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (866) 389-2727 (Main)\n\n",
	"field_org_lat_long": "40.736837500000, -73.988379900000",
	"field_org_distance": "0.32",
	"field_org_last_updated": "",
	"field_org_svc_testing": "Chlamydia Testing, Conventional Blood HIV Testing, Gonorrhea Testing, Hepatitis B Testing, Hepatitis C Testing, Rapid Oral HIV Testing, Syphilis Testing, TB Testing, Hepatitis C Rapid Testing",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Human Papillomavirus Vaccine, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), STD Treatment",
	"field_org_svc_support": "",
	"field_audiences": "General Public",
	"field_organization_languages": "English, Interpretation Services Available for Non-English Languages",
	"field_npin_link": "https://npin.cdc.gov/node/344411",
	"field_organization_hours": "Monday, 8:30am To 7:30pm, Tuesday, 8:30am To 7:30pm, Wednesday, 8:30am To 7:30pm, Thursday, 8:30am To 7:30pm, Friday, 8:30am To 7:30pm, Saturday, 9:00am To 5:30pm, Sunday, 10:00am To 5:30pm",
	"field_organization_eligibilty": "Please visit the website or call for eligibility requirements. \nSTD testing, HIV PrEP and PEP for patients 18+.\nTrichomoniasis testing available as part of STD testing services.",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicare Accepted",
	"field_org_emails": "",
	"last_updated": "3/27/20",
	"field_org_type": "CVS Partner,",
	"field_org_websites": "https://www.cvs.com/minuteclinic||"
}, {
	"field_org_nid": "327479",
	"field_org_id": "116975",
	"title_field": "Cortes and Velazquez Care Incorporated",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "247 3rd Ave",
	"field_org_street2": "Ste 501",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10010",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 260-7474 (Main)\n\n",
	"field_org_lat_long": "40.737064400000, -73.984103100000",
	"field_org_distance": "0.37",
	"field_org_last_updated": "2018-02-09 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "General Public, HIV Positive Persons, At Risk Persons, Persons with HIV/AIDS",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/327479",
	"field_organization_hours": "Monday,10:00am To 6:00pm, Tuesday,10:00am To 6:00pm, Wednesday,10:00am To 6:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicaid Accepted,Medicare Accepted,PrEP for uninsured",
	"field_org_emails": "",
	"last_updated": "1/27/20",
	"field_org_type": "Clinic,",
	"field_org_websites": ""
}, {
	"field_org_nid": "308107",
	"field_org_id": "6017",
	"title_field": "Planned Parenthood of Greater New York",
	"field_organization_name_2": "Margaret Sanger Center",
	"field_organization_name_3": "",
	"field_org_street1": "26 Bleecker St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10012",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 965-7000 (Main)\n\n, \n\n  \n  (212) 965-6996 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.725371900000, -73.993608600000",
	"field_org_distance": "0.58",
	"field_org_last_updated": "2018-01-23 00:00",
	"field_org_svc_testing": "Hepatitis C Testing, Gonorrhea Testing, Syphilis Testing, Herpes Testing, Chlamydia Testing, Rapid Blood HIV Testing, Conventional Blood HIV Testing",
	"field_org_svc_prevention": "Condom/Female Condom/Dental Dam Distribution, Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Human Papillomavirus Vaccine, STD Treatment, Medication Adherence Education and Counseling, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "Case Management, PrEP Navigation",
	"field_audiences": "General Public, Gay Men, HIV Positive Persons, Hispanics/Latinos, Adolescents/Youth/Teens, Asians/Pacific Islanders, At Risk Persons, African Americans/Blacks, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Native Americans, Persons with HIV/AIDS, Women",
	"field_organization_languages": "English, Interpretation Services Available for Non-English Languages, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/308107",
	"field_organization_hours": "Monday,8:00am To 8:30pm, Tuesday,8:00am To 8:30pm, Wednesday,8:00am To 8:30pm, Thursday,8:00am To 8:30pm, Friday,8:00am To 6:30pm, Saturday,8:00am To 5:30pm",
	"field_organization_eligibilty": "If you are uninsured, you may qualify for a state-funded program or a lower fee scale.",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicaid Accepted,PrEP for uninsured,Sliding Scale",
	"field_org_emails": "",
	"last_updated": "1/24/20",
	"field_org_type": "Clinic,Social Service Organization",
	"field_org_websites": "https://www.plannedparenthood.org/planned-parenthood-greater-new-york||"
}, {
	"field_org_nid": "306434",
	"field_org_id": "32265",
	"title_field": "National Alliance Medication Assisted Recovery",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "435 2nd Ave",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10010",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 595-6262 (Main)\n\n",
	"field_org_lat_long": "40.739055900000, -73.980315100000",
	"field_org_distance": "0.60",
	"field_org_last_updated": "2017-12-27 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "Hepatitis Prevention/Education, HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "Training Programs",
	"field_org_svc_care": "",
	"field_org_svc_support": "Research",
	"field_audiences": "Health Professionals, HIV Positive Persons, Persons with HIV/AIDS, Persons with Hepatitis, Injecting Drug Users/Needle Sharing Partners, Substance Abusers",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/306434",
	"field_organization_hours": "",
	"field_organization_eligibilty": "Organization is an advocacy recovery membership organization. There is a fee to join. Medication Assisted Treatment Certification as Advocate.",
	"field_org_fee": "lowcost,Donations Accepted,No Fee",
	"field_org_emails": "nama.info@methadone.org ",
	"last_updated": "1/13/20",
	"field_org_type": "Educational Organization/Institution,",
	"field_org_websites": "http://www.methadone.org||"
}, {
	"field_org_nid": "326823",
	"field_org_id": "116170",
	"title_field": "Village Park Medical",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "31 Washington Square W",
	"field_org_street2": "4th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 475-8833 (Main)\n\n",
	"field_org_lat_long": "40.731911200000, -73.999083300000",
	"field_org_distance": "0.61",
	"field_org_last_updated": "2017-10-12 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Human Papillomavirus Vaccine, STD Treatment, Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment, Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Hepatitis B Treatment, Hepatitis C Treatment",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "At Risk Persons, Persons with HIV/AIDS",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/326823",
	"field_organization_hours": "",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicare Accepted,PrEP for uninsured",
	"field_org_emails": "",
	"last_updated": "10/17/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "http://www.villageparkmedical.com||"
}, {
	"field_org_nid": "338896",
	"field_org_id": "338896",
	"title_field": "Manhattan Primary Care",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "55 W 17th St",
	"field_org_street2": "Ste 105",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 378-9987 (Main)\n\n",
	"field_org_lat_long": "40.739196100000, -73.994710400000",
	"field_org_distance": "0.61",
	"field_org_last_updated": "",
	"field_org_svc_testing": "Hepatitis A Testing, Hepatitis B Testing, Hepatitis C Testing, Conventional Blood HIV Testing, Rapid Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing",
	"field_org_svc_prevention": "Condom/Female Condom/Dental Dam Distribution, Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "STD Treatment, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), Hepatitis A Vaccine, Hepatitis B Treatment, Hepatitis C Treatment",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "Adolescents/Youth/Teens, African Americans/Blacks, Asians/Pacific Islanders, At Risk Persons, Gay Men, General Public, Hispanics/Latinos, HIV Positive Persons, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Native Americans, Persons with HIV/AIDS, Women",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/338896",
	"field_organization_hours": "Monday,8:00am To 7:00pm, Tuesday,8:00am To 7:00pm, Wednesday,8:00am To 7:00pm, Thursday,8:00am To 7:00pm, Friday,8:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Free Hepatitis B Testing,Free Hepatitis C Testing,Free HIV Testing,Free STD Testing,Insurance Accepted,Medicaid Accepted,PrEP for uninsured,Sliding Scale",
	"field_org_emails": "info@manhattanprimarycaredoctorsnyc.com",
	"last_updated": "11/12/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.manhattanprimarycaredoctorsnyc.com||, https://www.facebook.com/Manhattan-Primary-Care-2123706591256016/||, https://twitter.com/primarycarenyc||, https://www.linkedin.com/company/manhattan-primary-care||, https://www.instagram.com/manhattanprimarycare||"
}, {
	"field_org_nid": "345126",
	"field_org_id": "345126",
	"title_field": "CVS MinuteClinic",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "298 Mulberry St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "",
	"field_org_state": "NY",
	"field_org_zipcode": "10012",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (866) 389-2727 (Main)\n\n",
	"field_org_lat_long": "40.725088400000, -73.994412400000",
	"field_org_distance": "0.62",
	"field_org_last_updated": "",
	"field_org_svc_testing": "Chlamydia Testing, Conventional Blood HIV Testing, Gonorrhea Testing, Hepatitis B Testing, Hepatitis C Testing, Rapid Oral HIV Testing, Syphilis Testing, TB Testing, Hepatitis C Rapid Testing",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Human Papillomavirus Vaccine, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), STD Treatment",
	"field_org_svc_support": "",
	"field_audiences": "General Public",
	"field_organization_languages": "English, Interpretation Services Available for Non-English Languages",
	"field_npin_link": "https://npin.cdc.gov/node/345126",
	"field_organization_hours": "Monday, 8:30am To 7:30pm, Tuesday, 8:30am To 7:30pm, Wednesday, 8:30am To 7:30pm, Thursday, 8:30am To 7:30pm, Friday, 8:30am To 7:30pm, Saturday, 9:00am To 5:30pm, Sunday, 10:00am To 5:30pm",
	"field_organization_eligibilty": "Please visit the website or call for eligibility requirements. \nSTD testing, HIV PrEP and PEP for patients 18+.\nTrichomoniasis testing available as part of STD testing services.",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicare Accepted",
	"field_org_emails": "",
	"last_updated": "3/27/20",
	"field_org_type": "CVS Partner,",
	"field_org_websites": "https://www.cvs.com/minuteclinic||"
}, {
	"field_org_nid": "328339",
	"field_org_id": "328339",
	"title_field": "Mount Sinai ",
	"field_organization_name_2": "Mount Sinai Doctors",
	"field_organization_name_3": "",
	"field_org_street1": "94 E 1st St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10009",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 677-2157 (Main)\n\n",
	"field_org_lat_long": "40.723185200000, -73.986905500000",
	"field_org_distance": "0.63",
	"field_org_last_updated": "2018-09-18 11:54",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Primary Care, Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "",
	"field_audiences": "At Risk Persons",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/328339",
	"field_organization_hours": "Monday,8:00am To 5:00pm, Tuesday,8:00am To 5:00pm, Wednesday,10:00am To 6:00pm, Thursday,9:00am To 5:00pm, Friday,8:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "Fee",
	"field_org_emails": "",
	"last_updated": "11/19/19",
	"field_org_type": "Hospital,Clinic",
	"field_org_websites": "https://www.mountsinai.org||"
}, {
	"field_org_nid": "338901",
	"field_org_id": "338901",
	"title_field": "Manhattan Primary Care ",
	"field_organization_name_2": "Midtown Office",
	"field_organization_name_3": "",
	"field_org_street1": "51 E 25th St",
	"field_org_street2": "Ste 453",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10010",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 389-1877 (Main)\n\n",
	"field_org_lat_long": "40.741920600000, -73.986123200000",
	"field_org_distance": "0.67",
	"field_org_last_updated": "",
	"field_org_svc_testing": "Hepatitis A Testing, Hepatitis B Testing, Hepatitis C Testing, Chlamydia Testing, Gonorrhea Testing",
	"field_org_svc_prevention": "Condom/Female Condom/Dental Dam Distribution, Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "STD Treatment, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment, Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Hepatitis B Treatment, Hepatitis C Treatment",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "Adolescents/Youth/Teens, African Americans/Blacks, Asians/Pacific Islanders, At Risk Persons, Gay Men, General Public, Hispanics/Latinos, HIV Positive Persons, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Native Americans, Persons with HIV/AIDS, Women",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/338901",
	"field_organization_hours": "Monday,8:00am To 7:00pm, Tuesday,8:00am To 7:00pm, Wednesday,8:00am To 7:00pm, Thursday,8:00am To 7:00pm, Friday,8:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "Fee",
	"field_org_emails": "info@manhattanprimarycaredoctorsnyc.com",
	"last_updated": "11/13/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.manhattanprimarycaredoctorsnyc.com||, https://www.facebook.com/Manhattan-Primary-Care-2123706591256016/||, https://twitter.com/primarycarenyc||, https://www.linkedin.com/company/manhattan-primary-care||, https://www.instagram.com/manhattanprimarycare||"
}, {
	"field_org_nid": "306839",
	"field_org_id": "111653",
	"title_field": "Center for Drug Use and HIV Research",
	"field_organization_name_2": "New York HIV Research Consortium",
	"field_organization_name_3": "",
	"field_org_street1": "433 1st Ave",
	"field_org_street2": "7th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10010",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 998-5300 (Main)\n\n, \n\n  \n  (212) 995-3143 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.738683400000, -73.977768800000",
	"field_org_distance": "0.67",
	"field_org_last_updated": "2018-05-02 10:30",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "Capacity Building, Funding to Organizations, Program Administration, Research, Training Programs",
	"field_org_svc_care": "",
	"field_org_svc_support": "Research",
	"field_audiences": "Health Professionals, Persons with HIV/AIDS, Researchers",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/306839",
	"field_organization_hours": "",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "cduhr.nursing@nyu.edu",
	"last_updated": "2/10/20",
	"field_org_type": "Educational Organization/Institution,",
	"field_org_websites": "http://www.cduhr.org/||"
}, {
	"field_org_nid": "301502",
	"field_org_id": "31972",
	"title_field": "FHI 360",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "381 Park Ave S",
	"field_org_street2": "Ste 701",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 243-1110 (Main)\n\n",
	"field_org_lat_long": "40.742380400000, -73.984200600000",
	"field_org_distance": "0.72",
	"field_org_last_updated": "2017-12-18 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "Materials \u2013 Print/Audiovisual, HIV/AIDS Prevention Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "Public Awareness Campaigns, Technical Assistance, Training Programs",
	"field_org_svc_care": "",
	"field_org_svc_support": "Behavioral Research, Research",
	"field_audiences": "Community Based Organizations, Developing Nations, Educators, Health Professionals, Persons with TB",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/301502",
	"field_organization_hours": "Monday,8:00am To 5:30pm, Tuesday,8:00am To 5:30pm, Wednesday,8:00am To 5:30pm, Thursday,8:00am To 5:30pm, Friday,8:00am To 5:30pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "Fee",
	"field_org_emails": "",
	"last_updated": "11/12/19",
	"field_org_type": "Educational Organization/Institution,",
	"field_org_websites": "https://www.fhi360.org/||, http://facebook.com/FHI360||, http://twitter.com/fhi360||"
}, {
	"field_org_nid": "301674",
	"field_org_id": "32514",
	"title_field": "National AIDS Treatment Advocacy Project",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "580 Broadway",
	"field_org_street2": "Ste 1010",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10012",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 219-0106 (Main)\n\n, \n\n  \n  (888) 266-2827 (Toll Free)\n\n, \n\n  \n  (212) 219-8473 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.724592300000, -73.997209400000",
	"field_org_distance": "0.74",
	"field_org_last_updated": "2017-10-03 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "Electronic Information Resources, Hepatitis Prevention/Education, HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "Advocacy/Activism, Technical Assistance, Training Programs",
	"field_org_svc_care": "",
	"field_org_svc_support": "",
	"field_audiences": "General Public, HIV Positive Persons, Low Income Persons, Men, Persons with Hepatitis, Persons with HIV/AIDS, Women, Young Adults",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/301674",
	"field_organization_hours": "",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "info@natap.org",
	"last_updated": "9/26/19",
	"field_org_type": "Educational Organization/Institution,",
	"field_org_websites": "http://www.natap.org||"
}, {
	"field_org_nid": "327471",
	"field_org_id": "116982",
	"title_field": "Northwell Health ",
	"field_organization_name_2": "Physician Partners at Chelsea North",
	"field_organization_name_3": "",
	"field_org_street1": "121A W 20th St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 505-6663 (Main)\n\n",
	"field_org_lat_long": "40.741479900000, -73.994879300000",
	"field_org_distance": "0.75",
	"field_org_last_updated": "2018-02-09 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Primary Care, Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "At Risk Persons, General Public",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/327471",
	"field_organization_hours": "Monday,9:00am To 5:30pm, Tuesday,9:00am To 5:30pm, Wednesday,9:00am To 5:30pm, Thursday,9:00am To 5:30pm, Friday,9:00am To 5:30pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,PrEP for uninsured",
	"field_org_emails": "nhppwest20thstreet@northwell.edu",
	"last_updated": "9/6/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.northwell.edu/doctors-offices/northwell-health-physician-partners-at-chelsea-north||"
}, {
	"field_org_nid": "301145",
	"field_org_id": "5018",
	"title_field": "Village Care of New York",
	"field_organization_name_2": "Adult Day Health Care",
	"field_organization_name_3": "",
	"field_org_street1": "121 B W 20th St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 337-9220 (Main)\n\n, \n\n  \n  (212) 633-6587 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.741576800000, -73.994855300000",
	"field_org_distance": "0.75",
	"field_org_last_updated": "2018-02-02 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "Training Programs",
	"field_org_svc_care": "Substance Abuse Treatment, HIV/AIDS Medical Treatment",
	"field_org_svc_support": "",
	"field_audiences": "At Risk Persons, HIV Positive Persons, Injecting Drug Users/Needle Sharing Partners, Low Income Persons, Persons with HIV/AIDS, Substance Abusers",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/301145",
	"field_organization_hours": "Monday,8:30am To 5:30pm, Tuesday,8:30am To 5:30pm, Wednesday,8:30am To 5:30pm, Thursday,8:30am To 3:00pm, Friday,8:30am To 4:00pm, Saturday,10:00am To 2:00pm, Sunday,10:00am To 2:00pm",
	"field_organization_eligibilty": "Day and Evening services for people who living with or are at risk of HIV/AIDS ages 18 and up, and eligible for Medicaid.",
	"field_org_fee": "lowcost,Medicaid Accepted",
	"field_org_emails": "info@vcny.org",
	"last_updated": "9/12/19",
	"field_org_type": "Community Based Organization,AIDS Service Organization",
	"field_org_websites": "||, www.facebook.com/villagecareNY/||, twitter.com/VillageCare||"
}, {
	"field_org_nid": "327472",
	"field_org_id": "116983",
	"title_field": "New York University Langone Health",
	"field_organization_name_2": "Dr Ricky Hsu",
	"field_organization_name_3": "",
	"field_org_street1": "154 W 14th St",
	"field_org_street2": "4th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York ",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 627-7560 (Main)\n\n",
	"field_org_lat_long": "40.738109400000, -73.999588700000",
	"field_org_distance": "0.76",
	"field_org_last_updated": "2018-02-09 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Primary Care, Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "At Risk Persons, General Public",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/327472",
	"field_organization_hours": "",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted",
	"field_org_emails": "",
	"last_updated": "9/6/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://nyulangone.org/doctors/1568491967/ricky-k-hsu||"
}, {
	"field_org_nid": "343972",
	"field_org_id": "343972",
	"title_field": "Manhattan Medical Arts",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "123 W 20 St",
	"field_org_street2": "",
	"field_org_city_name": "Manhattan",
	"field_org_county": "New York ",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (646) 454-9000 (ext 3) (Main)\n\n",
	"field_org_lat_long": "40.741670500000, -73.995107800000",
	"field_org_distance": "0.77",
	"field_org_last_updated": "",
	"field_org_svc_testing": "Hepatitis A Testing, Hepatitis C Testing, Hepatitis B Testing, TB Testing, Gonorrhea Testing, Syphilis Testing, Herpes Testing, Chlamydia Testing, Conventional Blood HIV Testing",
	"field_org_svc_prevention": "Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "TB Treatment, Human Papillomavirus Vaccine, STD Treatment, Medication Adherence Education and Counseling, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), Adult Hepatitis B Vaccine, Hepatitis A Vaccine",
	"field_org_svc_support": "",
	"field_audiences": "General Public, Gay Men, HIV Positive Persons, Hispanics/Latinos, Adolescents/Youth/Teens, Asians/Pacific Islanders, At Risk Persons, African Americans/Blacks, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Native Americans, Persons with HIV/AIDS, Women",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/343972",
	"field_organization_hours": "Monday,8:45am To 7:30pm, Tuesday,8:45am To 7:30pm, Wednesday,8:45am To 7:30pm, Thursday,8:45am To 7:30pm, Friday,11:00am To 5:30pm, Saturday,9:00am To 2:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicaid Accepted,Sliding Scale",
	"field_org_emails": "ops@mmedicalarts.com",
	"last_updated": "1/24/20",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.manhattanmedicalarts.com||, https://m.facebook.com/manhattanmedicalarts||"
}, {
	"field_org_nid": "306836",
	"field_org_id": "34861",
	"title_field": "Center for Special Studies",
	"field_organization_name_2": "Judith Peabody Wellness Center",
	"field_organization_name_3": "David Rogers Unit",
	"field_org_street1": "53 W 23rd St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10001",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 746-7200 (Main)\n\n, \n\n  \n  (212) 746-7200 (Other phone number)\n\n",
	"field_org_lat_long": "40.742960600000, -73.991313000000",
	"field_org_distance": "0.77",
	"field_org_last_updated": "2018-08-16 11:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "HIV/AIDS Prevention Education, Partner Notification",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Gynecological Care, Primary Care, Medication Adherence Education and Counseling, Pre-Exposure Prophylaxis (PrEP), Clinical Trials, HIV/AIDS Medical Treatment",
	"field_org_svc_support": "Case Management, Drug Purchasing Assistance, including AIDS Drug Purchasing Assistance (ADAP), PrEP Navigation, Support Groups",
	"field_audiences": "Adults, HIV Positive Persons, Low Income Persons, Persons with HIV/AIDS, Sex Partners, Young Adults",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/306836",
	"field_organization_hours": "Monday,9:00am To 3:00pm, Tuesday,9:00am To 12:00pm, Wednesday,9:00am To 3:00pm, Thursday,9:00am To 3:00pm, Friday,9:00am To 3:00pm",
	"field_organization_eligibilty": "No HIV testing is offered but comprehensive HIV care seen by social workers and doctors is offered.",
	"field_org_fee": "lowcost,Fee,Medicaid Accepted,Medicare Accepted",
	"field_org_emails": "",
	"last_updated": "8/13/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.nyp.org/hiv-pep-prep||"
}, {
	"field_org_nid": "306600",
	"field_org_id": "18528",
	"title_field": "Latino Commission on AIDS",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "24 W 25th St",
	"field_org_street2": "9th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10010",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (646) 238-4578 (HIV/AIDS Services)\n\n, \n\n  \n  (212) 675-3466 (Domestic Fax)\n\n, \n\n  \n  (212) 675-3288 (Main)\n\n",
	"field_org_lat_long": "40.743293000000, -73.990409600000",
	"field_org_distance": "0.78",
	"field_org_last_updated": "2017-10-20 00:00",
	"field_org_svc_testing": "Hepatitis C Testing, Conventional Blood HIV Testing, Rapid Blood HIV Testing",
	"field_org_svc_prevention": "Materials \u2013 Print/Audiovisual, Condom/Female Condom/Dental Dam Distribution, Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, Street Outreach",
	"field_org_svc_capacity": "Public Awareness Campaigns, Technical Assistance, Training Programs",
	"field_org_svc_care": "Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "Case Management",
	"field_audiences": "Adolescents/Youth/Teens, Adults, African Americans/Blacks, At Risk Persons, At Risk Youth, Foreign Born/Immigrants, Gay Men, General Public, Hispanics/Latinos, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Minorities, Persons Practicing High Risk Behaviors, Persons with Hepatitis, Persons with HIV/AIDS, Women, Young Adults",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/306600",
	"field_organization_hours": "Monday,9:30am To 4:00pm, Tuesday,9:30am To 4:00pm, Wednesday,9:30am To 4:00pm, Thursday,9:30am To 4:00pm, Friday,9:30am To 4:00pm",
	"field_organization_eligibilty": "HIV testing open to the general public.",
	"field_org_fee": "lowcost,Donations Accepted,Free Hepatitis C Testing,Free HIV Testing,No Fee",
	"field_org_emails": "gmorales@latinoaids.org",
	"last_updated": "9/19/19",
	"field_org_type": "AIDS Service Organization,",
	"field_org_websites": "www.latinoaids.org||"
}, {
	"field_org_nid": "306432",
	"field_org_id": "21507",
	"title_field": "National Development and Research Institutes Incorporated",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "71 W 23rd St",
	"field_org_street2": "4th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10010",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 845-4400 (Main)\n\n, \n\n  \n  (917) 438-0894 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.742952900000, -73.992284300000",
	"field_org_distance": "0.78",
	"field_org_last_updated": "2018-08-16 13:30",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "Electronic Information Resources, Materials \u2013 Print/Audiovisual",
	"field_org_svc_capacity": "Training Programs",
	"field_org_svc_care": "",
	"field_org_svc_support": "Behavioral Research, Research",
	"field_audiences": "Health Professionals, Researchers",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/306432",
	"field_organization_hours": "Monday,8:30am To 5:30pm, Tuesday,8:30am To 5:30pm, Wednesday,8:30am To 5:30pm, Thursday,8:30am To 5:30pm, Friday,8:30am To 5:30pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "sendusanemail@ndri.org",
	"last_updated": "8/14/19",
	"field_org_type": "Educational Organization/Institution,",
	"field_org_websites": "www.ndri.org||, www.facebook.com/ndri1967/||"
}, {
	"field_org_nid": "306797",
	"field_org_id": "109245",
	"title_field": "Housing Works Incorporated",
	"field_organization_name_2": "Keith D Cylar House Health Center",
	"field_organization_name_3": "",
	"field_org_street1": "743-749 E 9th St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10009",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 677-7999 (Main)\n\n, \n\n  \n  (212) 614-1844 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.724602300000, -73.976015300000",
	"field_org_distance": "0.80",
	"field_org_last_updated": "2018-02-16 00:00",
	"field_org_svc_testing": "Hepatitis A Testing, Hepatitis C Testing, Hepatitis B Testing, TB Testing, Gonorrhea Testing, Syphilis Testing, Herpes Testing, Chlamydia Testing, Rapid Blood HIV Testing, Conventional Blood HIV Testing",
	"field_org_svc_prevention": "Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "TB Treatment, STD Treatment, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment, Adult Hepatitis B Vaccine, Hepatitis A Vaccine",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "General Public, HIV Positive Persons, Low Income Persons, Men, Persons with HIV/AIDS, Women",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/306797",
	"field_organization_hours": "Monday,8:30am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "Testing open to the general public. Adult Day Treatment clients must be HIV-positive and eligible for Medicaid.",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicaid Accepted,PrEP for uninsured,Sliding Scale",
	"field_org_emails": "",
	"last_updated": "12/30/19",
	"field_org_type": "Community Based Organization,",
	"field_org_websites": "https://healthcare.housingworks.org/locations/location-3||, https://www.facebook.com/housingworks.org/||, https://www.twitter.com/housingworks||"
}, {
	"field_org_nid": "306914",
	"field_org_id": "897",
	"title_field": "NYC Health and Hospitals ",
	"field_organization_name_2": "Bellevue ",
	"field_organization_name_3": "",
	"field_org_street1": "462 1st Ave",
	"field_org_street2": "Bldg A 4th  Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 562-4038 (Main)\n\n",
	"field_org_lat_long": "40.739072900000, -73.975016500000",
	"field_org_distance": "0.80",
	"field_org_last_updated": "2018-06-18 15:15",
	"field_org_svc_testing": "Hepatitis A Testing, Hepatitis B Testing, Hepatitis C Testing, Conventional Blood HIV Testing, Rapid Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Herpes Testing, Syphilis Testing, TB Testing",
	"field_org_svc_prevention": "Condom/Female Condom/Dental Dam Distribution, Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "Technical Assistance, Workplace Programs",
	"field_org_svc_care": "STD Treatment, Medication Adherence Education and Counseling, HIV/AIDS Medical Treatment, Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Hepatitis C Treatment",
	"field_org_svc_support": "Case Management, Drug Purchasing Assistance, including AIDS Drug Purchasing Assistance (ADAP)",
	"field_audiences": "Adolescents/Youth/Teens, African Americans/Blacks, At Risk Persons, Gay Men, General Public, Hispanics/Latinos, HIV Positive Persons, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Persons with HIV/AIDS, Women",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/306914",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 8:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Free HIV Testing,Sliding Scale",
	"field_org_emails": "",
	"last_updated": "12/16/19",
	"field_org_type": "Clinic,Hospital",
	"field_org_websites": "https://www.nychealthandhospitals.org/bellevue/hiv-services||"
}, {
	"field_org_nid": "303852",
	"field_org_id": "21087",
	"title_field": "Community Healthcare Network",
	"field_organization_name_2": "Catherine M Abate Health Center",
	"field_organization_name_3": "",
	"field_org_street1": "150 Essex St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10002",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 477-1120 (Main)\n\n, \n\n  \n  (866) 246-8259 (Toll Free)\n\n, \n\n  \n  (212) 477-8957 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.720559400000, -73.986905500000",
	"field_org_distance": "0.81",
	"field_org_last_updated": "2018-07-30 10:30",
	"field_org_svc_testing": "Hepatitis A Testing, Hepatitis B Testing, Hepatitis C Testing, Conventional Blood HIV Testing, Rapid Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Herpes Testing, Syphilis Testing, TB Testing",
	"field_org_svc_prevention": "Condom/Female Condom/Dental Dam Distribution, Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, Safer Sex Education, STD Prevention/Education, Street Outreach",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Family Planning, Gynecological Care, Primary Care, Medication Adherence Education and Counseling, Adult Hepatitis B Vaccine, Hepatitis A Vaccine, HIV/AIDS Medical Treatment, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), Human Papillomavirus Vaccine, STD Treatment, TB Treatment",
	"field_org_svc_support": "Case Management, Drug Purchasing Assistance, including AIDS Drug Purchasing Assistance (ADAP), PrEP Navigation",
	"field_audiences": "General Public, Homeless Persons, HIV Positive Persons, Adults, Adolescents/Youth/Teens, Low Income Persons, Persons Practicing High Risk Behaviors, Persons with Hepatitis, Persons with HIV/AIDS, Persons with STDs, Persons with TB, Pregnant Adolescents, Pregnant Women, Sex Partners, Substance Abusers, Women, Young Adults",
	"field_organization_languages": "English, Interpretation Services Available for Non-English Languages, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/303852",
	"field_organization_hours": "Monday,8:00am To 8:00pm, Tuesday,8:00am To 5:00pm, Wednesday,8:00am To 8:00pm, Thursday,8:00am To 5:00pm, Friday,8:00am To 5:00pm, Saturday,9:00am To 4:00pm",
	"field_organization_eligibilty": "Always accept new patients and never turn anyone away. No patient will be denied services based on an inability to pay.",
	"field_org_fee": "lowcost,Fee,Free HIV Testing,Insurance Accepted,Medicaid Accepted,Medicare Accepted,PrEP for uninsured,Sliding Scale",
	"field_org_emails": "info@chnnyc.org",
	"last_updated": "5/20/19",
	"field_org_type": "Clinic,Federally Qualified Health Center (FQHC)",
	"field_org_websites": "www.chnnyc.org/our-locations/catherine-m-abate-health-center-formerly-the-downtown-health-center||, www.facebook.com/chnnyc/||"
}, {
	"field_org_nid": "306344",
	"field_org_id": "24051",
	"title_field": "The LGBT Community Center",
	"field_organization_name_2": "Health Services",
	"field_organization_name_3": "",
	"field_org_street1": "208 W 13th St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (646) 556-9300 (Main)\n\n",
	"field_org_lat_long": "40.738087000000, -74.001046000000",
	"field_org_distance": "0.82",
	"field_org_last_updated": "2018-07-02 15:00",
	"field_org_svc_testing": "Rapid Blood HIV Testing",
	"field_org_svc_prevention": "HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education",
	"field_org_svc_capacity": "Training Programs",
	"field_org_svc_care": "",
	"field_org_svc_support": "",
	"field_audiences": "Adolescents/Youth/Teens, African Americans/Blacks, Asians/Pacific Islanders, At Risk Persons, Gay Men, General Public, Hispanics/Latinos, HIV Positive Persons, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Native Americans, Persons with HIV/AIDS, Women",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/306344",
	"field_organization_hours": "Monday,12:00pm To 4:00pm, Tuesday,12:00pm To 4:00pm, Wednesday,12:00pm To 4:00pm, Thursday,12:00pm To 4:00pm, Friday,12:00pm To 4:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Free HIV Testing,No Fee",
	"field_org_emails": "hivservices@gaycenter.org",
	"last_updated": "1/6/20",
	"field_org_type": "Community Based Organization,",
	"field_org_websites": "https://gaycenter.org||, https://www.facebook.com/lgbtcenternyc||, https://twitter.com/LGBTCenterNYC||"
}, {
	"field_org_nid": "299906",
	"field_org_id": "896",
	"title_field": "William F Ryan Community Health Network",
	"field_organization_name_2": "Ryan-NENA Community Health Center",
	"field_organization_name_3": "",
	"field_org_street1": "279 E 3rd St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10009",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 477-8500 (Main)\n\n, \n\n  \n  (212) 473-4970 (Domestic Fax)\n\n, \n\n  \n  (212) 477-8518 (Other phone number)\n\n",
	"field_org_lat_long": "40.721571800000, -73.980056300000",
	"field_org_distance": "0.83",
	"field_org_last_updated": "2018-01-27 00:00",
	"field_org_svc_testing": "TB Testing, Gonorrhea Testing, Syphilis Testing, Herpes Testing, Chlamydia Testing, Rapid Blood HIV Testing",
	"field_org_svc_prevention": "Harm Reduction, Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Family Planning, TB Treatment, Human Papillomavirus Vaccine, STD Treatment, Primary Care, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), Adult Hepatitis B Vaccine, Hepatitis A Vaccine",
	"field_org_svc_support": "Case Management",
	"field_audiences": "General Public, HIV Positive Persons, Adolescents/Youth/Teens, At Risk Persons, Adults, Injecting Drug Users/Needle Sharing Partners, Low Income Persons, Persons Practicing High Risk Behaviors, Persons with HIV/AIDS, Persons with STDs, Persons with TB",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/299906",
	"field_organization_hours": "Monday,8:30am To 7:00pm, Tuesday,8:30am To 4:30pm, Wednesday,8:30am To 4:30pm, Thursday,8:30am To 7:00pm, Friday,8:30am To 4:30pm, Saturday,9:30am To 1:00pm",
	"field_organization_eligibilty": "Need to enroll as a patient.",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicaid Accepted,Medicare Accepted,Sliding Scale",
	"field_org_emails": "info@ryan-nena.org",
	"last_updated": "1/17/20",
	"field_org_type": "Clinic,Federally Qualified Health Center (FQHC)",
	"field_org_websites": "ryanhealth.org||, www.facebook.com/ryanhealthnyc/||, twitter.com/RyanHealthNYC||"
}, {
	"field_org_nid": "301478",
	"field_org_id": "100806",
	"title_field": "MAC AIDS Fund",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "130 Prince St",
	"field_org_street2": "2nd Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10012",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 965-6300 (Main)\n\n, \n\n  \n  (212) 372-6171 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.725365100000, -74.000591700000",
	"field_org_distance": "0.84",
	"field_org_last_updated": "2018-01-25 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "Funding to Organizations, Grant Management, Public Awareness Campaigns",
	"field_org_svc_care": "",
	"field_org_svc_support": "",
	"field_audiences": "Community Based Organizations",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/301478",
	"field_organization_hours": "Monday,8:00am To 5:00pm, Tuesday,8:00am To 5:00pm, Wednesday,8:00am To 5:00pm, Thursday,8:00am To 5:00pm, Friday,8:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "macaidsf@maccosmetics.com",
	"last_updated": "1/17/20",
	"field_org_type": "Foundation,",
	"field_org_websites": "https://m.maccosmetics.com/vivaglam-timeline||"
}, {
	"field_org_nid": "326978",
	"field_org_id": "116343",
	"title_field": "Mount Sinai ",
	"field_organization_name_2": "Mount Sinai Doctors ",
	"field_organization_name_3": "",
	"field_org_street1": "226 W 14th St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 604-1800 (Main)\n\n",
	"field_org_lat_long": "40.738966000000, -74.001252200000",
	"field_org_distance": "0.86",
	"field_org_last_updated": "2017-10-12 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Family Planning, STD Treatment, Primary Care, Pre-Exposure Prophylaxis (PrEP), Hepatitis A Vaccine",
	"field_org_svc_support": "",
	"field_audiences": "At Risk Persons, General Public, LGBT",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/326978",
	"field_organization_hours": "Monday,8:00am To 8:00pm, Tuesday,8:00am To 8:00pm, Wednesday,8:00am To 8:00pm, Thursday,8:00am To 8:00pm, Friday,8:00am To 5:00pm, Saturday,9:00am To 2:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicare Accepted,PrEP for uninsured",
	"field_org_emails": "",
	"last_updated": "11/19/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.mountsinai.org/locations/msd-west-14||"
}, {
	"field_org_nid": "326824",
	"field_org_id": "116171",
	"title_field": "NYC Health and Hospitals",
	"field_organization_name_2": "Gouverneur ",
	"field_organization_name_3": "Judson Health Care Center",
	"field_org_street1": "34 Spring St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10012",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 925-5000 (Main)\n\n",
	"field_org_lat_long": "40.721550400000, -73.995886800000",
	"field_org_distance": "0.86",
	"field_org_last_updated": "2017-10-12 00:00",
	"field_org_svc_testing": "Conventional Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Syphilis Testing",
	"field_org_svc_prevention": "HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Primary Care, Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "",
	"field_audiences": "At Risk Persons, Persons with HIV/AIDS",
	"field_organization_languages": "Chinese, English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/326824",
	"field_organization_hours": "",
	"field_organization_eligibilty": "Must become a patient of the clinic to receive services. Please arrive 1 hour before appt. if you are a new patient.",
	"field_org_fee": "Fee,PrEP for uninsured",
	"field_org_emails": "",
	"last_updated": "11/19/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.nychealthandhospitals.org/gouverneur?s=judson||"
}, {
	"field_org_nid": "306834",
	"field_org_id": "34547",
	"title_field": "Harm Reduction Coalition",
	"field_organization_name_2": "New York Office",
	"field_organization_name_3": "",
	"field_org_street1": "22 W 27th St",
	"field_org_street2": "5th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10001",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 213-6376 (Main)\n\n, \n\n  \n  (212) 213-6582 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.744640500000, -73.989674600000",
	"field_org_distance": "0.86",
	"field_org_last_updated": "2018-08-16 13:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "Harm Reduction, Hepatitis Prevention/Education, HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "Technical Assistance, Training Programs",
	"field_org_svc_care": "",
	"field_org_svc_support": "",
	"field_audiences": "African Americans/Blacks, At Risk Persons, Community Based Organizations, Gay Men, Health Professionals, Hispanics/Latinos, Injecting Drug Users/Needle Sharing Partners, LGBT, Low Income Persons, Men Who Have Sex with Men, Substance Abusers, Women",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/306834",
	"field_organization_hours": "Friday,9:00am To 5:00pm, Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Donations Accepted,No Fee",
	"field_org_emails": "hrc@harmreduction.org",
	"last_updated": "3/18/20",
	"field_org_type": "Educational Organization/Institution,",
	"field_org_websites": "https://harmreduction.org||, https://www.facebook.com/HarmReductionCoalition||, https://twitter.com/HarmReduction||"
}, {
	"field_org_nid": "306724",
	"field_org_id": "28341",
	"title_field": "Chinese-American Planning Council, Inc",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "165 Eldridge St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10002",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (646) 613-8420 (Main)\n\n, \n\n  \n  (646) 226-5351 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.720035700000, -73.991244200000",
	"field_org_distance": "0.87",
	"field_org_last_updated": "2018-08-16 11:15",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "Training Programs, Technical Assistance, Public Awareness Campaigns",
	"field_org_svc_care": "",
	"field_org_svc_support": "Case Management",
	"field_audiences": "Asians/Pacific Islanders, At Risk Persons, HIV Positive Persons, Low Income Persons, Persons with HIV/AIDS",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/306724",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "chs@cpc-nyc.org",
	"last_updated": "12/23/19",
	"field_org_type": "Community Based Organization,",
	"field_org_websites": "https://www.cpc-nyc.org/programs/community-economic-empowerment/community-health-services||, https://twitter.com/cpc_nyc||, https://www.instagram.com/cpcchs/||"
}, {
	"field_org_nid": "328074",
	"field_org_id": "117073",
	"title_field": "Institute for Family Health",
	"field_organization_name_2": "17th Street Clinic ",
	"field_organization_name_3": "",
	"field_org_street1": "230 W 17th St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 206-5200 (Main)\n\n",
	"field_org_lat_long": "40.740951200000, -73.999838000000",
	"field_org_distance": "0.89",
	"field_org_last_updated": "",
	"field_org_svc_testing": "Hepatitis A Testing, Hepatitis C Testing, Hepatitis B Testing, TB Testing, Gonorrhea Testing, Syphilis Testing, Herpes Testing, Chlamydia Testing, Rapid Blood HIV Testing, Conventional Blood HIV Testing",
	"field_org_svc_prevention": "HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Family Planning, Primary Care, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment, Adult Hepatitis B Vaccine, Hepatitis A Vaccine",
	"field_org_svc_support": "Case Management",
	"field_audiences": "General Public, Adolescents/Youth/Teens, At Risk Persons, Low Income Persons, Men, Women",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/328074",
	"field_organization_hours": "Monday, 8:00am To 8:00pm, Tuesday, 8:00am To 8:00pm, Wednesday, 8:00am To 8:00pm, Thursday, 8:00am To 8:00pm, Friday, 8:00am To 6:00pm, Saturday, 8:00am To 6:00pm, Sunday, 8:00am To 6:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Free HIV Testing,Insurance Accepted,Medicaid Accepted,Sliding Scale",
	"field_org_emails": "",
	"last_updated": "1/27/20",
	"field_org_type": "Clinic,Federally Qualified Health Center (FQHC)",
	"field_org_websites": "https://www.institute.org/health-care/locations/manhattan||, https://www.facebook.com/InstituteForFamilyHealth||"
}, {
	"field_org_nid": "328362",
	"field_org_id": "328362",
	"title_field": "Bethany Medical Clinic ",
	"field_organization_name_2": "Murray Hill Office",
	"field_organization_name_3": "",
	"field_org_street1": "222 E 31st St",
	"field_org_street2": "Ste 1R",
	"field_org_city_name": "New York",
	"field_org_county": "New York ",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (646) 586-2293 (Main)\n\n",
	"field_org_lat_long": "40.743275500000, -73.978613300000",
	"field_org_distance": "0.89",
	"field_org_last_updated": "2018-09-24 09:16",
	"field_org_svc_testing": "Hepatitis B Testing, Hepatitis C Testing, Conventional Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Herpes Testing, Syphilis Testing, TB Testing",
	"field_org_svc_prevention": "Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "Training Programs",
	"field_org_svc_care": "Family Planning, STD Treatment, Primary Care, Medication Adherence Education and Counseling, Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment, Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Hepatitis B Treatment, Hepatitis C Treatment",
	"field_org_svc_support": "Case Management, Drug Purchasing Assistance, including AIDS Drug Purchasing Assistance (ADAP), Housing Opportunities for Persons with AIDS/HOPWA",
	"field_audiences": "Gay Men, General Public, Hispanics/Latinos, African Americans/Blacks, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Native Americans, Women",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/328362",
	"field_organization_hours": "Monday,8:00am To 8:00pm, Tuesday, 8:00am To 8:00pm, Wednesday,8:00am To 8:00pm, Thursday,8:00am To 8:00pm, Friday,8:00am To 4:00pm, Saturday,10:00am To 6:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicaid Accepted,Medicare Accepted",
	"field_org_emails": "mail@bmcofny.com",
	"last_updated": "7/15/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.bmcofny.com||"
}, {
	"field_org_nid": "306800",
	"field_org_id": "100769",
	"title_field": "GBC Health",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "44 W 28th St",
	"field_org_street2": "Ste 1800",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10001",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 218-4180 (Main)\n\n",
	"field_org_lat_long": "40.745569400000, -73.989966800000",
	"field_org_distance": "0.93",
	"field_org_last_updated": "2018-08-16 11:45",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "Materials \u2013 Print/Audiovisual, HIV/AIDS Prevention Education, TB Prevention Education",
	"field_org_svc_capacity": "Technical Assistance",
	"field_org_svc_care": "",
	"field_org_svc_support": "Research",
	"field_audiences": "Developing Nations, Persons with HIV/AIDS, Persons with TB",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/306800",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "Fee",
	"field_org_emails": "",
	"last_updated": "8/13/19",
	"field_org_type": "Social Service Organization,",
	"field_org_websites": "www.gbchealth.org||, www.facebook.com/GBCHealth||, www.youtube.com/user/gbchealth||, twitter.com/gbchealth||"
}, {
	"field_org_nid": "305634",
	"field_org_id": "111486",
	"title_field": "Project Renewal Incorporated",
	"field_organization_name_2": "Primary Care",
	"field_organization_name_3": "",
	"field_org_street1": "200 Varick St",
	"field_org_street2": "9th floor",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10014",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 620-0340 (Main)\n\n",
	"field_org_lat_long": "40.728124900000, -74.005009100000",
	"field_org_distance": "0.96",
	"field_org_last_updated": "2017-07-06 00:00",
	"field_org_svc_testing": "Hepatitis B Testing, Hepatitis C Testing, Conventional Blood HIV Testing, Rapid Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Herpes Testing, Syphilis Testing, TB Testing",
	"field_org_svc_prevention": "Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education, Street Outreach, TB Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Family Planning, STD Treatment, Primary Care, Medication Adherence Education and Counseling, HIV/AIDS Medical Treatment, Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Hepatitis B Treatment",
	"field_org_svc_support": "Case Management, Drug Purchasing Assistance, including AIDS Drug Purchasing Assistance (ADAP), Housing Opportunities for Persons with AIDS/HOPWA",
	"field_audiences": "Gay Men, General Public, Hispanics/Latinos, Homeless Persons, At Risk Persons, Adults, African Americans/Blacks, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Older Adults, Women, Young Adults",
	"field_organization_languages": "English, French, Interpretation Services Available for Non-English Languages, Russian, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/305634",
	"field_organization_hours": "",
	"field_organization_eligibilty": "Testing open to general public. Free HIV and STD testing services provided if the client does not have insurance.",
	"field_org_fee": "lowcost,Free Hepatitis B Testing,Free Hepatitis C Testing,Free HIV Testing,Free STD Testing,Free TB Testing,No Fee",
	"field_org_emails": "",
	"last_updated": "7/23/19",
	"field_org_type": "Clinic,Federally Qualified Health Center (FQHC)",
	"field_org_websites": "http://www.projectrenewal.org/health-3||"
}, {
	"field_org_nid": "302979",
	"field_org_id": "35",
	"title_field": "Gods Love We Deliver",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "166 Ave of the Americas",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10013",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 294-8100 (Main)\n\n, \n\n  \n  (800) 747-2023 (Toll Free)\n\n, \n\n  \n  (212) 294-8101 (Domestic Fax)\n\n, \n\n  \n  (212) 294-8102 (Other phone number)\n\n",
	"field_org_lat_long": "40.725573000000, -74.003655300000",
	"field_org_distance": "0.97",
	"field_org_last_updated": "2017-11-13 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "",
	"field_org_svc_support": "Food Services",
	"field_audiences": "Adults, HIV Positive Persons, Low Income Persons, Persons with HIV/AIDS",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/302979",
	"field_organization_hours": "Monday,8:00am To 8:00pm, Tuesday,8:00am To 8:00pm, Wednesday,8:00am To 8:00pm, Thursday,8:00am To 8:00pm, Friday,8:00am To 8:00pm",
	"field_organization_eligibilty": "Call for eligibility requirements.",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "clientservices@glwd.org",
	"last_updated": "10/8/19",
	"field_org_type": "Community Based Organization,",
	"field_org_websites": "www.glwd.org||, www.facebook.com/godslovewedeliver||, twitter.com/godslovenyc||"
}, {
	"field_org_nid": "328123",
	"field_org_id": "117421",
	"title_field": "Concorde Medical Group",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "38 E 32nd St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 352-0549 (Main)\n\n",
	"field_org_lat_long": "40.745972400000, -73.983150600000",
	"field_org_distance": "0.97",
	"field_org_last_updated": "2018-07-27 09:30",
	"field_org_svc_testing": "Conventional Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Herpes Testing, Syphilis Testing, TB Testing",
	"field_org_svc_prevention": "Hepatitis Prevention/Education, HIV Test Counseling, HIV/AIDS Prevention Education, STD Prevention/Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Family Planning, Primary Care, Medication Adherence Education and Counseling, Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Hepatitis B Treatment, Hepatitis C Treatment, HIV/AIDS Medical Treatment, Pre-Exposure Prophylaxis (PrEP), Human Papillomavirus Vaccine, STD Treatment",
	"field_org_svc_support": "",
	"field_audiences": "Gay Men, General Public, Hispanics/Latinos, African Americans/Blacks, LGBT, Men, Men Who Have Sex with Men, Native Americans, Women",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/328123",
	"field_organization_hours": "Monday,8:30am To 4:00pm, Tuesday,8:30am To 4:00pm, Wednesday,8:30am To 4:00pm, Thursday,8:30am To 4:00pm, Friday,8:30am To 4:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicare Accepted",
	"field_org_emails": "",
	"last_updated": "5/20/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "concordemed.com||"
}, {
	"field_org_nid": "302319",
	"field_org_id": "10004",
	"title_field": "NYU Langone Health",
	"field_organization_name_2": "Pediatric Infectious Diseases",
	"field_organization_name_3": "",
	"field_org_street1": "550 1st Ave",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 263-5940 (Main)\n\n",
	"field_org_lat_long": "40.742122500000, -73.973964200000",
	"field_org_distance": "0.98",
	"field_org_last_updated": "2017-11-14 00:00",
	"field_org_svc_testing": "TB Testing",
	"field_org_svc_prevention": "HIV Test Counseling, HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "TB Treatment, HIV/AIDS Medical Treatment, Hepatitis C Treatment",
	"field_org_svc_support": "Case Management",
	"field_audiences": "Adolescents with HIV/AIDS, General Public, HIV Positive Persons, Infants/Children with HIV/AIDS, Low Income Persons, Parents/Families of Persons with HIV/AIDS, Women with HIV/AIDS, including Pregnant Women with HIV/AIDS",
	"field_organization_languages": "Chinese, English, Haitian Creole, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/302319",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicaid Accepted",
	"field_org_emails": "",
	"last_updated": "11/19/19",
	"field_org_type": "Clinic,Hospital",
	"field_org_websites": "https://nyulangone.org/locations/nyu-langone-pediatric-infectious-diseases/doctors||"
}, {
	"field_org_nid": "307697",
	"field_org_id": "110682",
	"title_field": "NYU School of Medicine",
	"field_organization_name_2": "Department of Population Health",
	"field_organization_name_3": "Section for Health Equity",
	"field_org_street1": "550 1st Ave",
	"field_org_street2": "VZN 8th Floor",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 263-1225 (Main)\n\n, \n\n  \n  (212) 263-4086 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.742122500000, -73.973964200000",
	"field_org_distance": "0.98",
	"field_org_last_updated": "2017-04-20 00:00",
	"field_org_svc_testing": "Hepatitis C Testing",
	"field_org_svc_prevention": "Harm Reduction, Hepatitis Prevention/Education",
	"field_org_svc_capacity": "Public Awareness Campaigns",
	"field_org_svc_care": "Hepatitis C Treatment",
	"field_org_svc_support": "Research",
	"field_audiences": "General Public, Foreign Born/Immigrants, Hispanics/Latinos, Adolescents/Youth/Teens, Asians/Pacific Islanders, African Americans/Blacks, Adults, Community Based Organizations, LGBT, Low Income Persons, Men, Men Who Have Sex with Men, Persons Practicing High Risk Behaviors, Persons with Hepatitis, Women",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/307697",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "",
	"last_updated": "1/27/20",
	"field_org_type": "Educational Organization/Institution,",
	"field_org_websites": "https://med.nyu.edu/prevention-research/||, https://med.nyu.edu/asian-health/research/reachfar||"
}, {
	"field_org_nid": "305956",
	"field_org_id": "16248",
	"title_field": "Mount Sinai ",
	"field_organization_name_2": "Comprehensive Health Program",
	"field_organization_name_3": "Downtown Campus",
	"field_org_street1": "275 7th Ave",
	"field_org_street2": "12th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10011",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 604-1701 (Main)\n\n, \n\n  \n  (212) 604-1720 (Main)\n\n, \n\n  \n  (800) 637-4624 (Toll Free)\n\n",
	"field_org_lat_long": "40.745568400000, -73.994159900000",
	"field_org_distance": "0.99",
	"field_org_last_updated": "2018-07-02 15:15",
	"field_org_svc_testing": "Conventional Blood HIV Testing, Rapid Blood HIV Testing, Chlamydia Testing, Gonorrhea Testing, Herpes Testing, Syphilis Testing, TB Testing",
	"field_org_svc_prevention": "Condom/Female Condom/Dental Dam Distribution, HIV Test Counseling, HIV/AIDS Prevention Education, Safer Sex Education, STD Prevention/Education, TB Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Family Planning, TB Treatment, STD Treatment, Substance Abuse Treatment, Gynecological Care, Primary Care, Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment",
	"field_org_svc_support": "Case Management, Housing Services, PrEP Navigation, Support Groups",
	"field_audiences": "Adolescents/Youth/Teens, Adults, General Public, HIV Positive Persons, Low Income Persons, Persons Practicing High Risk Behaviors, Persons with HIV/AIDS, Persons with STDs, Persons with TB, Sex Partners, Substance Abusers, Women, Young Adults",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/305956",
	"field_organization_hours": "Monday, 9:00am To 3:30pm, Tuesday, 9:00am To 4:00pm, Wednesday, 9:00am To 4:00pm, Thursday, 9:00am To 4:00pm, Friday, 9:00am To 3:30pm",
	"field_organization_eligibilty": "Services provided regardless of ability to pay.",
	"field_org_fee": "lowcost,Fee,Free HIV Testing,Insurance Accepted,Medicaid Accepted,Medicare Accepted,PrEP for uninsured,Sliding Scale",
	"field_org_emails": "",
	"last_updated": "11/19/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.mountsinai.org/patient-care/service-areas/infectious-diseases/hiv-aids||"
}, {
	"field_org_nid": "326980",
	"field_org_id": "116345",
	"title_field": "NYU Langone Health",
	"field_organization_name_2": "NYU Lagone Medical Associates - Chelsea",
	"field_organization_name_3": "",
	"field_org_street1": "160 W 26th St",
	"field_org_street2": "3rd Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10001",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (646) 660-9999 (Main)\n\n",
	"field_org_lat_long": "40.745716500000, -73.993927100000",
	"field_org_distance": "0.99",
	"field_org_last_updated": "2017-10-12 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "TB Treatment, Primary Care, Pre-Exposure Prophylaxis (PrEP), HIV/AIDS Medical Treatment",
	"field_org_svc_support": "",
	"field_audiences": "At Risk Persons, General Public, Persons with HIV/AIDS",
	"field_organization_languages": "English, Korean, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/326980",
	"field_organization_hours": "",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted",
	"field_org_emails": "",
	"last_updated": "11/19/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://nyulangone.org/locations/nyu-langone-medical-associates-chelsea||"
}, {
	"field_org_nid": "326972",
	"field_org_id": "116337",
	"title_field": "Gotham Medical Group",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "314 W 14th St",
	"field_org_street2": "5th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10014",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 620-0144 (Main)\n\n",
	"field_org_lat_long": "40.739915800000, -74.003497300000",
	"field_org_distance": "0.99",
	"field_org_last_updated": "2017-10-12 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Primary Care, Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "At Risk Persons, General Public",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/326972",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicare Accepted",
	"field_org_emails": "",
	"last_updated": "10/17/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "http://gothammed.com||"
}, {
	"field_org_nid": "306979",
	"field_org_id": "30742",
	"title_field": "Care for the Homeless",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "30 E 33rd St",
	"field_org_street2": "5th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 366-4459 (Main)\n\n, \n\n  \n  (212) 366-1773 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.746643200000, -73.982962900000",
	"field_org_distance": "1.02",
	"field_org_last_updated": "2018-08-16 10:45",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "HIV/AIDS Prevention Education, Street Outreach",
	"field_org_svc_capacity": "Program Administration",
	"field_org_svc_care": "",
	"field_org_svc_support": "Case Management, Housing Services",
	"field_audiences": "General Public, Homeless Persons, HIV Positive Persons, Low Income Persons, Persons Practicing High Risk Behaviors, Persons with HIV/AIDS, Sex Partners",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/306979",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "Must be homeless.",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "info@cfhnyc.org",
	"last_updated": "6/13/19",
	"field_org_type": "Community Based Organization,",
	"field_org_websites": "www.careforthehomeless.org||, www.facebook.com/careforthehomeless||"
}, {
	"field_org_nid": "345034",
	"field_org_id": "345034",
	"title_field": "CVS MinuteClinic",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "222 E 34th St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (866) 389-2727 (Main)\n\n",
	"field_org_lat_long": "40.744971700000, -73.977042400000",
	"field_org_distance": "1.03",
	"field_org_last_updated": "",
	"field_org_svc_testing": "Chlamydia Testing, Conventional Blood HIV Testing, Gonorrhea Testing, Hepatitis B Testing, Hepatitis C Testing, Rapid Oral HIV Testing, Syphilis Testing, TB Testing, Hepatitis C Rapid Testing",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Adult Hepatitis B Vaccine, Hepatitis A Vaccine, Human Papillomavirus Vaccine, Post Exposure Prophylaxis, Pre-Exposure Prophylaxis (PrEP), STD Treatment",
	"field_org_svc_support": "",
	"field_audiences": "General Public",
	"field_organization_languages": "English, Interpretation Services Available for Non-English Languages",
	"field_npin_link": "https://npin.cdc.gov/node/345034",
	"field_organization_hours": "Monday, 8:30am To 7:30pm, Tuesday, 8:30am To 7:30pm, Wednesday, 8:30am To 7:30pm, Thursday, 8:30am To 7:30pm, Friday, 8:30am To 7:30pm, Saturday, 9:00am To 5:30pm, Sunday, 10:00am To 5:30pm",
	"field_organization_eligibilty": "Please visit the website or call for eligibility requirements. \nSTD testing, HIV PrEP and PEP for patients 18+.\nTrichomoniasis testing available as part of STD testing services.",
	"field_org_fee": "lowcost,Fee,Insurance Accepted,Medicare Accepted",
	"field_org_emails": "",
	"last_updated": "3/27/20",
	"field_org_type": "CVS Partner,",
	"field_org_websites": "https://www.cvs.com/minuteclinic||"
}, {
	"field_org_nid": "305957",
	"field_org_id": "17566",
	"title_field": "Partnership for the Homeless",
	"field_organization_name_2": "",
	"field_organization_name_3": "",
	"field_org_street1": "305 7th Ave",
	"field_org_street2": "14th Fl",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10001",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 645-3444 (Main)\n\n, \n\n  \n  (212) 477-4663 (Domestic Fax)\n\n",
	"field_org_lat_long": "40.746654600000, -73.993345300000",
	"field_org_distance": "1.04",
	"field_org_last_updated": "2018-05-31 12:45",
	"field_org_svc_testing": "Rapid Blood HIV Testing",
	"field_org_svc_prevention": "Behavioral Interventions, HIV/AIDS Prevention Education",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Medication Adherence Education and Counseling",
	"field_org_svc_support": "Housing Services, Case Management, Housing Opportunities for Persons with AIDS/HOPWA",
	"field_audiences": "Homeless Persons",
	"field_organization_languages": "English, Spanish",
	"field_npin_link": "https://npin.cdc.gov/node/305957",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Donations Accepted,No Fee",
	"field_org_emails": "info@pfth.org",
	"last_updated": "3/27/20",
	"field_org_type": "Social Service Organization,",
	"field_org_websites": "https://partnershipforthehomeless.org||, https://www.facebook.com/pfthnyc||"
}, {
	"field_org_nid": "302512",
	"field_org_id": "7617",
	"title_field": "Design Industries Foundation Fighting AIDS",
	"field_organization_name_2": "National Office",
	"field_organization_name_3": "",
	"field_org_street1": "16 W 32nd St",
	"field_org_street2": "Ste 402",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 727-3100 (Main)\n\n",
	"field_org_lat_long": "40.747437400000, -73.986709300000",
	"field_org_distance": "1.05",
	"field_org_last_updated": "2017-08-03 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "Materials \u2013 Print/Audiovisual",
	"field_org_svc_capacity": "Advocacy/Activism, Funding to Organizations, Grant Management, Program Administration",
	"field_org_svc_care": "",
	"field_org_svc_support": "",
	"field_audiences": "Community Based Organizations, HIV Positive Persons, Parents/Families of Persons with HIV/AIDS, Persons with HIV/AIDS",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/302512",
	"field_organization_hours": "Monday,9:00am To 5:00pm, Tuesday,9:00am To 5:00pm, Wednesday,9:00am To 5:00pm, Thursday,9:00am To 5:00pm, Friday,9:00am To 5:00pm",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,No Fee",
	"field_org_emails": "info@diffa.org",
	"last_updated": "11/1/19",
	"field_org_type": "Foundation,",
	"field_org_websites": "https://diffa.org||"
}, {
	"field_org_nid": "326979",
	"field_org_id": "116344",
	"title_field": "CareMount Medical",
	"field_organization_name_2": "NYC - 317 East 34th Street",
	"field_organization_name_3": "",
	"field_org_street1": "317 E 34th St",
	"field_org_street2": "",
	"field_org_city_name": "New York",
	"field_org_county": "New York",
	"field_org_state": "NY",
	"field_org_zipcode": "10016",
	"field_org_country": "United States",
	"field_org_phone": "\n\n  \n  (212) 726-7400 (Main)\n\n",
	"field_org_lat_long": "40.744634900000, -73.974787100000",
	"field_org_distance": "1.08",
	"field_org_last_updated": "2017-10-12 00:00",
	"field_org_svc_testing": "",
	"field_org_svc_prevention": "",
	"field_org_svc_capacity": "",
	"field_org_svc_care": "Primary Care, Pre-Exposure Prophylaxis (PrEP)",
	"field_org_svc_support": "PrEP Navigation",
	"field_audiences": "At Risk Persons, General Public",
	"field_organization_languages": "English",
	"field_npin_link": "https://npin.cdc.gov/node/326979",
	"field_organization_hours": "",
	"field_organization_eligibilty": "",
	"field_org_fee": "lowcost,Fee,Insurance Accepted",
	"field_org_emails": "",
	"last_updated": "10/18/19",
	"field_org_type": "Clinic,",
	"field_org_websites": "https://www.caremountmedical.com/directory/locations/show/new-york-317||"
}]